site_name: Auto Homelab Docs

# Folder to hydrate from (relative to repo root)
docs_dir: docs/tmp

# Optional: where to output the built site
# site_dir: site  # default is 'site'

# Plugins to enable
plugins:
  - search
  - macros
  - mkdocs-copy  # optional: for relocating hydrated files
  - gen-files:
      scripts:
        - scripts/gen_docs.py              # scaffolds base Markdown templates
        - scripts/gen_service_docs.py
        - scripts/gen_index.py             # creates hydration index if missing
        - scripts/gen_hydrated_docs.py     # injects countdown into hydrated .md files

# Variables for substitution
extra:
  GH_USERNAME: anguy079
  FORK_NAME: lsio-docker-radarr
  REPO_ORIGIN: linuxserver/docker-radarr
  DELETE_AFTER_DAYS: 1  # used in cleanup logic
  TARGET_FOLDER: services/radarr
  WORKFLOW_FILE: hydrate.yml
  # WORKFLOW_FILE: sync-lsio-docker-radarr.yml  # not in template file
  COUNTDOWN_SNIPPET: |
    <div id="countdown"></div>
    <script>
      const endTime = new Date("{{ COUNTDOWN_END }}");
      const countdown = document.getElementById("countdown");
      setInterval(() => {
        const now = new Date();
        const diff = endTime - now;
        const hours = Math.floor(diff / 3600000);
        const minutes = Math.floor((diff % 3600000) / 60000);
        countdown.textContent = `Time remaining: ${hours}h ${minutes}m`;
      }, 60000);
    </script>
  COUNTDOWN_END: "2025-09-02T03:00:00Z"  # used in countdown timer

# Optional: theme settings
# theme:
#   name: material
#   palette:
#     primary: blue
#     accent: pink

# Optional: navigation structure
nav:
  - Hydration Preview: index.md
#  - MkDocs:
#      - Overview: docs/mkdocs/mkdocs-overview.md
#      - Getting Started: docs/mkdocs/README.md
#  - Templates:
#      - Forking Guide: docs/github/template-forking.md
#      - Radarr Sync: docs/services/radarr/sync-guide.md
