site_name: Auto Homelab Docs
docs_dir: docs/tmp

plugins:
  - search
  - macros
  - mkdocs-copy
  - gen-files:
      scripts:
        - scripts/gen_docs.py
        - scripts/gen_service_docs.py
        - scripts/gen_index.py
        - scripts/gen_hydrated_docs.py
        - scripts/gen_nav.py

extra:
  # GH_USERNAME and REPO_ORIGIN are now set by the workflow
  FORK_NAME: lsio-docker-radarr
  DELETE_AFTER_DAYS: 1
  TARGET_FOLDER: services/radarr
  WORKFLOW_FILE: hydrate.yml
  COUNTDOWN_SNIPPET: |
    <div id="countdown" class="countdown-badge">⏳ Calculating...</div>
    <script>
      const endTime = new Date("{{ COUNTDOWN_END }}");
      const countdown = document.getElementById("countdown");
      setInterval(() => {
        const now = new Date();
        const diff = endTime - now;
        const hours = Math.floor(diff / 3600000);
        const minutes = Math.floor((diff % 3600000) / 60000);

        countdown.textContent = `⏳ Expires in: ${hours}h ${minutes}m`;

        countdown.classList.remove("badge-green", "badge-yellow", "badge-red");
        if (diff > 12 * 3600000) {
          countdown.classList.add("badge-green");
        } else if (diff > 3 * 3600000) {
          countdown.classList.add("badge-yellow");
        } else {
          countdown.classList.add("badge-red");
        }
      }, 60000);
    </script>
  COUNTDOWN_END: '2025-09-02T03:00:00Z'

theme:
  name: material
  custom_dir: overrides
  extra_css:
    - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - ':droplet: Hydration Preview': index.md
