site_name: Auto Homelab Docs

# Folder to hydrate from (relative to repo root)
docs_dir: docs/tmp

# Optional: where to output the built site
# site_dir: site  # default is 'site'

# Plugins to enable
plugins:
  - search
  - macros
  - mkdocs-copy  # optional: for relocating hydrated files
  - gen-files:
      scripts:
        - scripts/gen_index.py

# Variables for substitution
extra:
  GH_USERNAME: anguy079
  FORK_NAME: lsio-docker-radarr
  REPO_ORIGIN: linuxserver/docker-radarr
  DELETE_AFTER_DAYS: 1  # used in cleanup logic
  TARGET_FOLDER: services/radarr
  WORKFLOW_FILE: hydrate.yml
  # WORKFLOW_FILE: sync-lsio-docker-radarr.yml  # not in template file
  COUNTDOWN_END: "2025-09-02T03:00:00Z"  # used in countdown timer

# Optional: theme settings
# theme:
#   name: material
#   palette:
#     primary: blue
#     accent: pink

# Optional: navigation structure
nav:
  - Hydration Preview: index.md
#  - MkDocs:
#      - Overview: docs/mkdocs/mkdocs-overview.md
#      - Getting Started: docs/mkdocs/README.md
#  - Templates:
#      - Forking Guide: docs/github/template-forking.md
#      - Radarr Sync: docs/services/radarr/sync-guide.md
