site_name: Auto Homelab Docs
site_url: https://placeholder.com # This is a placeholder updated by the workflow

docs_dir: docs/tmp

plugins:
  - search
  - macros
  - mkdocs-copy
  - gen-files:
      scripts:
        - scripts/gen_docs.py
        - scripts/gen_service_docs.py
        - scripts/gen_index.py
        - scripts/gen_hydrated_docs.py
        - scripts/gen_nav.py
        - scripts/gen_debug_page.py

extra:
  # These variables are read from the workflow environment
  REPO_FULL_NAME: "{{ env.REPO_FULL_NAME }}"
  REPO_OWNER: "{{ env.REPO_OWNER }}"
  REPO_NAME: "{{ env.REPO_NAME }}"
  REPO_URL: "{{ env.REPO_URL }}"
  REF_NAME: "{{ env.REF_NAME }}"
  LAST_UPDATED_BY: "{{ env.LAST_UPDATED_BY }}"
  COMMIT_SHA: "{{ env.COMMIT_SHA }}"
  WORKFLOW_RUN: "{{ env.WORKFLOW_RUN }}"

  # Static variables
  FORK_NAME: lsio-docker-radarr
  DELETE_AFTER_DAYS: 1
  TARGET_FOLDER: services/radarr
  WORKFLOW_FILE: hydrate.yml
  
  # This is a placeholder updated by the workflow
  COUNTDOWN_END: '2025-01-01T00:00:00Z'

theme:
  name: material
  custom_dir: overrides
  extra_css:
    - stylesheets/extra.css

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - ':droplet: Hydration Preview': index.md
