site_name: Auto Homelab Docs
# site_url will be filled in by the configuration script

docs_dir: docs/tmp

plugins:
  - search
  - macros
  - awesome-pages
  - gen-files:
      scripts:
        - scripts/hydrate.py

# The 'extra' block below will be populated automatically by scripts/configure_mkdocs.py
extra: {}

theme:
  name: material
  custom_dir: overrides

markdown_extensions:
  - attr_list
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
