site_name: Auto Homelab Docs
site_url: https://anguy079.github.io/auto-homelab
docs_dir: docs/tmp
plugins:
- search
- macros
- mkdocs-copy
- gen-files:
    scripts:
    - scripts/gen_docs.py
    - scripts/gen_service_docs.py
    - scripts/gen_index.py
    - scripts/gen_hydrated_docs.py
    - scripts/gen_nav.py
extra:
  REPO_FULL_NAME: '{{ env.REPO_FULL_NAME }}'
  REPO_OWNER: '{{ env.REPO_OWNER }}'
  REPO_NAME: '{{ env.REPO_NAME }}'
  REPO_URL: '{{ env.REPO_URL }}'
  REF_NAME: '{{ env.REF_NAME }}'
  LAST_UPDATED_BY: '{{ env.LAST_UPDATED_BY }}'
  COMMIT_SHA: '{{ env.COMMIT_SHA }}'
  WORKFLOW_RUN: '{{ env.WORKFLOW_RUN }}'
  FORK_NAME: lsio-docker-radarr
  DELETE_AFTER_DAYS: 1
  TARGET_FOLDER: services/radarr
  WORKFLOW_FILE: hydrate.yml
  COUNTDOWN_SNIPPET: "<div id=\"countdown\" class=\"countdown-badge\">\u23F3 Calculating...</div>\n\
    <script>\n  const endTime = new Date(\"{{ COUNTDOWN_END }}\");\n  const countdown\
    \ = document.getElementById(\"countdown\");\n  setInterval(() => {\n    const\
    \ now = new Date();\n    const diff = endTime - now;\n    const hours = Math.floor(diff\
    \ / 3600000);\n    const minutes = Math.floor((diff % 3600000) / 60000);\n\n \
    \   countdown.textContent = `\u23F3 Expires in: ${hours}h ${minutes}m`;\n\n  \
    \  countdown.classList.remove(\"badge-green\", \"badge-yellow\", \"badge-red\"\
    );\n    if (diff > 12 * 3600000) {\n      countdown.classList.add(\"badge-green\"\
    );\n    } else if (diff > 3 * 3600000) {\n      countdown.classList.add(\"badge-yellow\"\
    );\n    } else {\n      countdown.classList.add(\"badge-red\");\n    }\n  }, 60000);\n\
    </script>\n"
  COUNTDOWN_END: '2025-09-02T22:14:44+00:00'
theme:
  name: material
  custom_dir: overrides
  extra_css:
  - stylesheets/extra.css
markdown_extensions:
- attr_list
- pymdownx.emoji:
    emoji_index: !!python/name:material.extensions.emoji.twemoji ''
    emoji_generator: !!python/name:material.extensions.emoji.to_svg ''
nav:
- ':droplet: Hydration Preview': index.md
- ':file: Variable Test': variable-test.md
