name: Scheduled Cleanup

on:
  schedule:
    - cron: '0 * * * *'  # every hour
  workflow_dispatch: {} # Allows manual runs

jobs:
  cleanup-expired-docs:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Required to push changes
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install PyYAML
        run: pip install PyYAML

      - name: Check Expiry and Cleanup
        id: check_expiry
        run: |
          python -c "
          import yaml, sys
          from datetime import datetime, timezone

          try:
              with open('mkdocs.yml', 'r') as f:
                  config = yaml.safe_load(f)
                  end_time_str = config.get('extra', {}).get('COUNTDOWN_END')
          except FileNotFoundError:
              print('mkdocs.yml not found. Exiting.')
              sys.exit(0)
          
          if not end_time_str:
              print('COUNTDOWN_END not found in mkdocs.yml. Exiting.')
              sys.exit(0)

          end_time = datetime.fromisoformat(end_time_str.replace('Z', '+00:00'))
          now_time = datetime.now(timezone.utc)

          if now_time >= end_time:
              print('Hydration has expired. Cleaning up files.')
              sys.exit(1) # Exit with error code to signal cleanup
          else:
              print('Hydration still active. No cleanup needed.')
              sys.exit(0)
          " || echo "CLEANUP_NEEDED=true" >> $GITHUB_ENV

      - name: Perform Cleanup
        if: env.CLEANUP_NEEDED == 'true'
        run: |
          echo "Proceeding with cleanup..."
          git rm -rf --ignore-unmatch docs/tmp/*
          mkdir -p docs/tmp/
          touch docs/tmp/.gitkeep
          git add -f docs/tmp/.gitkeep
          sed -i "s|🕒 Hydrated on: .*|🕒 Hydrated on: **Not active**|" README.md
          sed -i "s|⏳ Expires in: .*|⏳ Expires in: **Expired**|" README.md
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Docs: Cleanup expired hydration"
          git push
