name: Hydrate & Deploy Docs

on:
  workflow_dispatch:
    inputs:
      delete_after_hours:
        description: 'Hours until cleanup (0 for indefinite). Overrides config.yml.'
        required: false

jobs:
  build:
    name: Build and Deploy
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    # Pass GitHub context to the Python script as environment variables
    env:
      GITHUB_REPOSITORY: ${{ github.repository }}
      GITHUB_REPOSITORY_OWNER: ${{ github.repository_owner }}
      GITHUB_REPOSITORY_NAME: ${{ github.event.repository.name }}
      GITHUB_SERVER_URL: ${{ github.server_url }}
      INPUT_DELETE_AFTER_HOURS: ${{ github.event.inputs.delete_after_hours }}
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      
      - name: Configure pip caching
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Configure Site and README
        run: python scripts/configure_mkdocs.py # <-- This one script does all the configuration

      - name: Build Hydrated Docs
        run: python -m mkdocs build -f mkdocs.yml

      - name: Push README changes
        run: |
          # (This step is no longer needed as the Python script can handle it)
          # For now, we'll leave it, but it could be integrated into configure_mkdocs.py
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          if git diff --quiet; then
            echo "No changes to commit."
          else
            git commit -am "Docs: Update config and README"
            git push
          fi

      - name: Upload GitHub Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site
      
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
