name: Update README Timestamp

on:
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Update Timestamp in README
        run: |
          TIMESTAMP=$(date -u +"%b %d, %Y @ %H:%M UTC")
          sed -i "s|🕒 Hydrated on: .*|🕒 Hydrated on: **$TIMESTAMP**|" README.md
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git commit -am "Update hydration timestamp"
          git push
